
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 
  password:

development:
  <<: *default
  database: users_graphql_development

test:
  <<: *default
  database: users_graphql_test

production:
  <<: *default
  database: users_graphql_production
  username: users_graphql
  password: <%= ENV['USERS_GRAPHQL_DATABASE_PASSWORD'] %>
